POST http://localhost:8080/form_post  HTTP/1.1
Content-Type: application/x-www-form-urlencoded

name=foo
&nick=qa
&message=bar1111
###

GET http://localhost:8080/bar
###

GET http://localhost:8080/someDataFromReader
###

GET http://localhost:8080/getb
?field_a=aa
&field_b=bb
###
GET http://localhost:8080/getc
?field_a=paa
&field_c=cc